//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug
    {
        public int BugId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int ProjectId { get; set; }
        public System.DateTime DiscoverDate { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
