//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace BugTracker.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BugTrackerEntities : DbContext
    {
        public BugTrackerEntities()
            : base("name=BugTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            Database.SetInitializer<BugTrackerEntities>(new CreateDatabaseIfNotExists<BugTrackerEntities>());

            modelBuilder.Entity<Bug>().ToTable("Bugs");
            modelBuilder.Entity<InfoCard>().ToTable("InfoCards");
            modelBuilder.Entity<Project>().ToTable("Projects");
            modelBuilder.Entity<UserProfile>().ToTable("UserProfiles");
            modelBuilder.Entity<webpages_Membership>().ToTable("webpages_Membership");
            modelBuilder.Entity<webpages_Roles>().ToTable("webpages_Roles");

            base.OnModelCreating(modelBuilder);
        }
    
        public DbSet<Bug> Bugs { get; set; }
        public DbSet<InfoCard> InfoCards { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
