//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugTracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoCard
    {
        public InfoCard()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int UserId { get; set; }
        public int NumberOfProjects { get; set; }
        public int NumberOfBugs { get; set; }
        public System.DateTime LastActivity { get; set; }
        public string LastAction { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}
